name: my_innowise_pokemon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc_concurrency: ^0.2.5
  connectivity_plus: ^6.0.2
  dio: ^5.4.2+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  path_to_regexp: ^0.4.0
  sqflite: ^2.3.2
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/appIcon.png"
  min_sdk_android: 21 
  remove_alpha_ios: true

flutter:
  uses-material-design: true
